--Don't forget to connect into your database before executing...

CREATE TABLE Offices (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    Name VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE Services (
    Id INT IDENTITY(1,1)  NOT NULL PRIMARY KEY, 
    Name VARCHAR(50) NOT NULL, 
    Fee DECIMAL(18, 2) NOT NULL, 
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE Roles (
    Id INT NOT NULL PRIMARY KEY, 
	Name VARCHAR(50) NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULl DEFAULT GETDATE(),
)

CREATE TABLE Statuses (
    Id INT NOT NULL PRIMARY KEY, 
	Name VARCHAR(50) NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULl DEFAULT GETDATE(),
)


CREATE TABLE Requests (
    Id INT IDENTITY(1,1)  NOT NULL PRIMARY KEY, 
    TrackingId VARCHAR(50) NOT NULL DEFAULT LEFT(NEWID(), 8) UNIQUE, 
    OfficeId INT NOT NULL FOREIGN KEY REFERENCES Offices(Id) DEFAULT 1, 
    ServiceId INT NOT NULL FOREIGN KEY REFERENCES Services(Id) DEFAULT 1, 
    StatusId INT NOT NULL FOREIGN KEY REFERENCES Statuses(Id) DEFAULT 3, 
    UserNote VARCHAR(50) NULL,
    OfficeNote VARCHAR(50) NULL,
    FilePath VARCHAR(MAX) NULL,
	FileName VARCHAR(MAX) NULL,
	FileSize BIGINT NULL,
	FileExtension VARCHAR(50) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULl DEFAULT GETDATE(),
    FinishedAt DATETIME NULL
)

CREATE TABLE Users (
    Id INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
    FirstName VARCHAR(50) NULL,
    LastName VARCHAR(50) NULL,
    Email VARCHAR(50) NULL,
    Password VARCHAR(Max) NOT NULL,
	RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id) DEFAULT 1,
    --Verified VARCHAR(50) NULL,
    --Active VARCHAR(50) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULl DEFAULT GETDATE()
);

CREATE TABLE Authentications (
    Id INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
	Token VARCHAR(200) NOT NULL UNIQUE, 
    --UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id), 
	UserId INT NOT NULL, 
	RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id) DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    ExpiredAt DATETIME NOT NULL DEFAULT DATEADD(day, 2, Datediff(Day,0, GetDate()))
);

