--Don't forget to connect into your database before executing...

CREATE TABLE Offices (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    Name VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE Services (
    Id INT IDENTITY(1,1)  NOT NULL PRIMARY KEY, 
    Name VARCHAR(50) NOT NULL, 
    Fee DECIMAL(18, 2) NOT NULL, 
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE Requests (
    Id INT IDENTITY(1,1)  NOT NULL PRIMARY KEY, 
    TrackingId VARCHAR(50) NOT NULL DEFAULT LEFT(NEWID(), 8) UNIQUE, 
    OfficeId INT NOT NULL FOREIGN KEY REFERENCES Offices(Id) DEFAULT 1, 
    ServiceId INT NOT NULL FOREIGN KEY REFERENCES Services(Id) DEFAULT 1, 
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending', 
    UserNote VARCHAR(50) NULL,
    OfficeNote VARCHAR(50) NULL,
    FileData VARCHAR(MAX) NULL,
	FileName VARCHAR(50) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULl DEFAULT GETDATE(),
    FinishedAt DATETIME NULL
)

CREATE TABLE Users (
    Id INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
    UserNumber VARCHAR(50) NULL,
    FirstName VARCHAR(50) NULL,
    LastName VARCHAR(50) NULL,
    Position VARCHAR(50) NULL,
    Email VARCHAR(50) NULL,
    Password VARCHAR(50) NOT NULL,
    Role VARCHAR(50) NULL,
    Verified VARCHAR(50) NULL,
    Active VARCHAR(50) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
    UpdatedAt DATETIME NOT NULl DEFAULT GETDATE()
);